#ifndef FOREGROUND_IMG_H
#define FOREGROUND_IMG_H

#define FORE_OUTER 0b01000100
#define FORE_LOWER 0b11010101

#define FORE_GREEN 0b01110101
#define FORE_LEMON 0b10011001
#define FORE_YELOW 0b11011110

#define FOREGROUND_SIZE 6

unsigned char foreground_img[FOREGROUND_SIZE][FOREGROUND_SIZE] = {
    {FORE_OUTER, FORE_OUTER, FORE_OUTER, FORE_OUTER, FORE_OUTER, FORE_OUTER},
    {FORE_YELOW, FORE_YELOW, FORE_YELOW, FORE_YELOW, FORE_YELOW, FORE_YELOW},
    {FORE_LEMON, FORE_LEMON, FORE_GREEN, FORE_GREEN, FORE_GREEN, FORE_GREEN},
    {FORE_LEMON, FORE_GREEN, FORE_GREEN, FORE_GREEN, FORE_GREEN, FORE_LEMON},
    {FORE_GREEN, FORE_GREEN, FORE_GREEN, FORE_GREEN, FORE_LEMON, FORE_LEMON},
    {FORE_LOWER, FORE_LOWER, FORE_LOWER, FORE_LOWER, FORE_LOWER, FORE_LOWER},
};
#endif
