#ifndef FOREGROUND_IMG_H
#define FOREGROUND_IMG_H

#define FORE_OUTER 0x13
#define FORE_LOWER 0x04

#define FORE_GREEN 0x7A
#define FORE_LEMON 0x2D
#define FORE_YELOW 0xa3


#define FOREGROUND_COLOR 0x5A
#define FOREGROUND_SIZE 6

unsigned char foreground_img[FOREGROUND_SIZE][FOREGROUND_SIZE] = {
    {FORE_OUTER, FORE_OUTER, FORE_OUTER, FORE_OUTER, FORE_OUTER, FORE_OUTER},
    {FORE_YELOW, FORE_YELOW, FORE_YELOW, FORE_YELOW, FORE_YELOW, FORE_YELOW},
    {FORE_LEMON, FORE_LEMON, FORE_GREEN, FORE_GREEN, FORE_GREEN, FORE_GREEN},
    {FORE_LEMON, FORE_GREEN, FORE_GREEN, FORE_GREEN, FORE_GREEN, FORE_LEMON},
    {FORE_GREEN, FORE_GREEN, FORE_GREEN, FORE_GREEN, FORE_LEMON, FORE_LEMON},
    {FORE_LOWER, FORE_LOWER, FORE_LOWER, FORE_LOWER, FORE_LOWER, FORE_LOWER},
};
#endif
