#ifndef TUNNEL_IMG_H
#define  TUNNEL_IMG_H

//#define TUNNEL_DARK 0b01010000
//#define TUNNEL_LIGHT 0b11011110
#define TUNNEL_DARK 0b00111000
#define TUNNEL_LIGHT 0b00111100
#define TUNNEL_OUTER 0
#define TUNNEL_TOP_LAYER_SIZE 4

unsigned char tunnel_layer[1][20] = {
    {TUNNEL_OUTER, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_OUTER},
};

unsigned char tunnel_top[4][26] = {
    {TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER},
    {TUNNEL_OUTER, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_OUTER},
    {TUNNEL_OUTER, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_LIGHT, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_DARK, TUNNEL_OUTER},
    {TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER, TUNNEL_OUTER},
};
#endif
